---
- name: Add a new IP address record to Linode DNS using official modules
  hosts: localhost
  gather_facts: false
  vars:
      new_record_type: "A"            # Use "A" for IPv4 or "AAAA" for IPv6
  vars_files:
    - "{{ path_to_vault_file }}"

  tasks:
    - name: Create or update A record for the subdomain
      linode.cloud.domain_record:
        api_token: "{{ linode_api_token }}"
        domain: "{{ root_domain }}"
        name: "{{ target_subdomain }}"
        type: "{{ new_record_type }}"
        target: "{{ ip_address }}"
        ttl_sec: 60
        state: present
