---
- name: Provision Linode Infrastructure
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create Linode instance with custom interfaces
      linode.cloud.instance:
        state: present 
        api_token: "{{ linode_api_token }}"
        label: "{{ server_name }}"
        region: "{{ region }}"
        type: "{{ server_size }}"
        image: "{{ image }}"
        root_pass: "{{ emergency_password }}"
        disk_encryption: enabled
        metadata:
          user_data: "{{ lookup('ansible.builtin.file', user_data_path) }}"
        # 1. Enable modern interface object generation
        interface_generation: linode
        
        # 2. Structural conversion of your custom --interfaces JSON payload
        linode_interfaces:
          - vpc:
              subnet_id: "{{ subnet_id | int }}"
              ipv4:
                addresses:
                  - address: auto
                    primary: true
                    nat_1_1_address: auto   # <-- This automatically provisions your ONE allowed public IP
            firewall_id: "{{ firewall_id | int }}"
            default_route:
              ipv4: true
      register: linode_instance

    - name: Export clean variables to a local environment file
      ansible.builtin.copy:
        content: |
          PUBLIC_IP={{ linode_instance.linode_interfaces[0].vpc.ipv4.addresses[0].nat_1_1_address }}
          PRIVATE_IP={{ linode_instance.linode_interfaces[0].vpc.ipv4.addresses[0].address }}
        dest: "{{ server_ips_file }}"
      delegate_to: localhost
      changed_when: false

#need to test if the build machine is outside the VPC and also parameterise 1035
    - name: Pause until the custom port is open
      ansible.builtin.wait_for:
        host: "{{ linode_instance.linode_interfaces[0].vpc.ipv4.addresses[0].address }}"
        port: 1035
        state: started
        timeout: 300

    - name: Fetch SSH host keys from remote machine and add to known_hosts
      ansible.builtin.shell: |
        ssh-keyscan -p 1035 -H {{  linode_instance.linode_interfaces[0].vpc.ipv4.addresses[0].address }} >> ~/.ssh/known_hosts
      delegate_to: localhost
      changed_when: true

    - name: Pause until file exists on the new remote instance
      ansible.builtin.wait_for:
        path: "/home/{{ server_user }}/runtime/WEBSERVER_READY"
        state: present
        timeout: 1200
      delegate_to: "{{ linode_instance.linode_interfaces[0].vpc.ipv4.addresses[0].address }}"
      remote_user: "{{ server_user }}" 
      vars:
        ansible_port: 1035

    - name: Continue with next task
      ansible.builtin.debug:
        msg: "The file exists on the remote target. Continuing..."
