---
- name: Provision Linode VPC and Subnetwork
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    # CRITICAL: Forces local execution to use your pipx virtualenv with 'polling'
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    

  tasks:
    - name: Create a Linode VPC
      linode.cloud.vpc:
        api_token: "{{ linode_api_key}}"
        label: "{{ vpc_label }}"
        region: "{{ vpc_region }}"
        description: "{{ vpc_desc }}"
        state: present

    - name: Look up my Linode VPC
      linode.cloud.vpc_info:
        api_token: "{{ linode_api_key }}"
        label: "{{ vpc_label }}"
      register: vpc_results

    - name: Fail if the VPC was not found
      fail:
        msg: "VPC with label '{{ vpc_label }}' could not be found."
      when: vpc_results.vpc is not defined or not vpc_results.vpc

    - name: Set VPC ID as a fact
      set_fact:
        my_vpc_id: "{{ vpc_results.vpc.id }}"

    - name: Display the VPC ID
      debug:
        msg: "The ID for VPC '{{ vpc_label }}' is {{ my_vpc_id }}"

    - name: Create the Subnetwork inside the VPC
      linode.cloud.vpc_subnet:
        api_token: "{{ linode_api_key }}"
        vpc_id: "{{ my_vpc_id }}"
        label: "{{ subnetwork_label }}"
        ipv4: "{{ subnetwork_ipv4 }}"
        state: present
