  - |
    /bin/bash -c '
    webroot_directory="$(/bin/grep "^WEBROOT_DIRECTORY:" "${HOME}/runtime/application.dat" | /usr/bin/awk -F\':\' \'{print $NF}\')"
    cd "$webroot_directory"

    /usr/bin/sudo -u www-data /usr/local/bin/composer require drush/drush --no-interaction 

    if [ -f "${webroot_directory}/vendor/bin/drush.php" ]; then
        /bin/echo "/bin/chmod 755 ${webroot_directory}/vendor/bin/drush.php" > /usr/sbin/drush
        /bin/echo "/bin/chmod 755 ${webroot_directory}/vendor/drush/drush" >> /usr/sbin/drush
        /bin/echo "/usr/bin/sudo -u www-data /usr/bin/php ${webroot_directory}/vendor/bin/drush.php \$@" >> /usr/sbin/drush
        /bin/chmod 750 /usr/sbin/drush
    fi
    '
