#cloud-config

manage_resolv_conf: true
resolv_conf:
  nameservers:
    - '9.9.9.9'
    - '1.1.1.2'
    - '8.8.8.8'
    - '8.8.4.4'

users:
  - name: XXXXSERVER_USERXXXX
    passwd: 'XXXXSERVER_USER_PASSWORDXXXX'
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - 'XXXXSSH_PUBLIC_KEYXXXX'

ssh_pwauth: false

ssh_keys:
  XXXXALGORITHMXXXX_private: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    XXXXSSH_PRIVATE_KEYXXXX
    -----END OPENSSH PRIVATE KEY-----

timezone: 'XXXXTIMEZONEXXXX'
hostname: XXXXDATABASE_HOSTNAMEXXXX
manage_etc_hosts: true

keyboard:
  layout: gb

write_files:
  - content: |
      Port XXXXSSH_PORTXXXX
    path: /etc/ssh/sshd_config.d/99-hardening.conf
    owner: root:root
    permissions: '0644'

write_files:
  - encoding: gzip+b64
    content: XXXXDATABASE_CONFIGURATIONXXXX
    owner: XXXXSERVER_USERXXXX:root
    path: /home/XXXXSERVER_USERXXXX/runtime/database_configuration_settings.dat
    permissions: '0750'

  - encoding: gzip+b64
    content: XXXXBUILDSTYLES_SETTINGSXXXX
    owner: XXXXSERVER_USERXXXX:root
    path: /home/XXXXSERVER_USERXXXX/runtime/software.dat
    permissions: '0750'

  - encoding: gzip+b64
    content: XXXXFIREWALL_PORT_SETTINGSXXXX
    owner: XXXXSERVER_USERXXXX:root
    path: /home/XXXXSERVER_USERXXXX/runtime/firewall.dat
    permissions: '0750'

  - content: /home/XXXXSERVER_USERXXXX
    owner: root:root
    path: /home/homedir.dat
    permissions: '0644'

  - content: |
      ClientAliveInterval 60
      ClientAliveCountMax 2
    path: /home/XXXXSERVER_USERXXXX/.ssh/config
    owner: 'root:root'
    permissions: '0600'

  - content: |
      export LANGUAGE=en_GB.UTF-8
      export LANG=en_GB.UTF-8
      export LC_ALL=en_GB.UTF-8
    path: /etc/profile
    append: true

packages:
  - grub-efi-amd64
  - git
  - network-manager
  - software-properties-common
  - jq
  - rsync
  - cron
  - zip
  - unzip

runcmd:
  - locale-gen en_GB.UTF-8
  - update-locale LANG=en_GB.UTF-8
  - export HOME=/home/XXXXSERVER_USERXXXX && /bin/sh ${HOME}/installation/Update.sh
  - mkdir -p /home/XXXXSERVER_USERXXXX/.ssh /home/development /etc/ssh/sshd_config.d
  - /bin/cp /etc/ssh/ssh_host_XXXXALGORITHMXXXX_key /home/XXXXSERVER_USERXXXX/.ssh/id_XXXXALGORITHMXXXX_AGILE_DEPLOYMENT_BUILD_KEY_XXXXBUILD_IDENTIFIERXXXX
  - /bin/cp /etc/ssh/ssh_host_XXXXALGORITHMXXXX_key.pub /home/XXXXSERVER_USERXXXX/.ssh/id_XXXXALGORITHMXXXX_AGILE_DEPLOYMENT_BUILD_KEY_XXXXBUILD_IDENTIFIERXXXX.pub
  - /usr/bin/git clone -b XXXXGIT_BRANCHXXXX --single-branch https://XXXXGIT_PROVIDER_DOMAINXXXX/XXXXINFRASTRUCTURE_REPOSITORY_OWNERXXXX/adt-database-scripts.git /home/XXXXSERVER_USERXXXX/clone
  - /usr/bin/rsync -a /home/XXXXSERVER_USERXXXX/clone/ /home/XXXXSERVER_USERXXXX
  - /usr/bin/rsync -a /home/XXXXSERVER_USERXXXX/clone/ /home/development && /bin/chown -R www-data:www-data /home/development && /bin/rm -r /home/XXXXSERVER_USERXXXX/clone
  - /usr/bin/chown -R XXXXSERVER_USERXXXX:root /home/XXXXSERVER_USERXXXX
  - /bin/chmod 755 /home/XXXXSERVER_USERXXXX /home/XXXXSERVER_USERXXXX/runtime /home/development
  - /bin/chmod 700 /home/XXXXSERVER_USERXXXX/.ssh
  - /bin/chmod 600 /home/XXXXSERVER_USERXXXX/.ssh/id_XXXXALGORITHMXXXX_AGILE_DEPLOYMENT_BUILD_KEY_XXXXBUILD_IDENTIFIERXXXX*
  - /home/XXXXSERVER_USERXXXX/utilities/processing/RunServiceCommand.sh "ssh" restart
  - |
    export HOME=/home/XXXXSERVER_USERXXXX
    /bin/sh ${HOME}/utilities/software/InitialiseToolkitForDevelopment.sh
    /bin/sh ${HOME}/installation/InstallPackageManager.sh
    /bin/sh ${HOME}/installation/InstallEmailUtil.sh
    /bin/sh ${HOME}/installation/InstallGo.sh &
    /bin/sh ${HOME}/installation/InstallDatastoreTools.sh
    /bin/sh ${HOME}/installation/InstallFirewall.sh
    /bin/sh ${HOME}/installation/InstallVirusScanner.sh
    /bin/sh ${HOME}/installation/InstallDatabase.sh
    /bin/sh ${HOME}/db.sh &




