---
- name: Create the new DNS record
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ cloudflare_auth_zone_id }}/dns_records"
    method: POST
    headers:
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_global_api_key }}"
      Content-Type: "application/json"
    body_format: json
    body:
      type: "A"
      name: "{{ full_domain }}"
      content: "{{ ip_address }}" 
      ttl: 1
      proxied: true
    status_code: 
      - 200
      - 201
