---
- name: Delete all A records for a specific subdomain
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ path_to_vault_file }}"

  tasks:
    - name: Delete matching subdomain A records
      community.general.cloudflare_dns:
        api_token: "{{ cloudflare_api_token }}"
        zone: "{{ root_domain }}"
        record: "{{ target_subdomain }}"
        type: A
        state: absent
